spring.application.name=outdoor-activity
server.port=8080

weather.api.base-url=https://api.weatherapi.com/v1
weather.api.key=da5b41d1579042e8845203447262406
weather.api.forecast-days=2

logging.level.org.springframework.web=INFO
logging.level.org.example.outdoor=DEBUG